[book]
authors = ["Jelmer Noppert"]
language = "nl"
multilingual = false
src = "src"
title = "DevOps Thanos blog"

[output.linkcheck]
warning-policy = "ignore"

[output.html.fold]
enable = true
level = 2
